sudo: required

services:
  - docker

script:
  - (cd hamilton_launch_server && ./dockerize.sh init)
  - (cd hamilton_launch_server && ./dockerize.sh build lin)
  - (cd hamilton_launch_server && ./dockerize.sh build osx)
  - (cd hamilton_launch_server && ./dockerize.sh build win)
  - (cd hamilton_launch_server && ./dockerize.sh build rpi)
  - (cd hamilton_launch_board && ./dockerize.sh init)
  - (cd hamilton_launch_board && ./dockerize.sh run build)
  - (cd hamilton_launch_board && ./dockerize.sh run lint)

language: golang
