script:
  - (cd server && go build)
  - (cd hamilton_launch_board && ./dockerize.sh init)
  - (cd hamilton_launch_board && ./dockerize.sh install)
  - (cd hamilton_launch_board && ./dockerize.sh run build)
  - (cd hamilton_launch_board && ./dockerize.sh run lint)

language: golang
